config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  d_homebrew:
    dst: ~/.config/homebrew
    src: config/homebrew
  d_uberischt:
    dst: ~/.config/uberischt
    src: config/uberischt
  d_vscode:
    dst: ~/.config/vscode
    src: config/vscode
  f_chunkwmrc:
    dst: ~/.chunkwmrc
    src: chunkwmrc
  f_gitignore_global:
    dst: ~/.gitignore_global
    src: gitignore_global
  f_khdrc:
    dst: ~/.khdrc
    src: khdrc
profiles:
  gael-reyrol.local:
    dotfiles:
    - f_gitignore_global
    - d_homebrew
    - d_uberischt
    - d_vscode
    - f_chunkwmrc
    - f_khdrc
